# Generated by Django 3.2 on 2021-04-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPartsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'db_table': 'body_parts_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('img', models.CharField(max_length=255, verbose_name='image path')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'db_table': 'training_type_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingtypecategory',
            index=models.Index(fields=['name'], name='train_type_cat_name_idx'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.bodypartscategory', verbose_name='exercise category'),
        ),
        migrations.AddIndex(
            model_name='bodypartscategory',
            index=models.Index(fields=['name'], name='body_parts_cat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='exercise_name_idx'),
        ),
    ]
