# Generated by Django 3.2 on 2021-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image path'),
        ),
    ]
