# Generated by Django 3.2 on 2021-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_exercise_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='image path'),
        ),
    ]
