# Generated by Django 3.2 on 2021-08-23 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_auto_20210808_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='difficulty_value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='difficulty',
            field=models.CharField(choices=[('RPE', 'Rpe'), ('RIR', 'Rir'), ('Percentage', 'Percentage')], max_length=64),
        ),
    ]
